### ISSUE TITLE
unable to find local copy of grunt-template-jasmine-istanbul

### ISSUE THREAD

**Issue by stevekane** [zzo/baseapp#1]
I have tried to manually re-install the package to no avail thus far.  I have not yet been able to track down the problem but it does seem to be coming from the express: server task.

When I run `grunt-test` it says "unable to find local npm module grunt-template-jasmine-istanbul"

**Comment by zzo** [comment]
this is a warning from matchdep because the minmatch regexp 'grunt-*' is also trying to pull in the grunt istanbul template which is NOT a plugin so grunt warns - does not effect anything just lame.
I changed to regex to avoid this issue.
